### ISSUE TITLE
Exception: data type - 'Task'

### ISSUE THREAD

**Issue by gusevvasily** [deniszykov/WebSocketListener#32] opened 2018-10-17 22:06 UTC
Hello, @deniszykov!

I open a socket, the client connects, the code is executed, the answer is sent to the client, I catch an exception:
![screenshot_97](https://user-images.githubusercontent.com/21026700/47118867-791ed000-d271-11e8-8a69-657afb515fe9.png)

Code (for example MonoEchoServer code):
![screenshot_101](https://user-images.githubusercontent.com/21026700/47119018-03673400-d272-11e8-87b4-619f746c4439.png)
![screenshot_102](https://user-images.githubusercontent.com/21026700/47119020-04986100-d272-11e8-8f05-77482bb57591.png)
![screenshot_103](https://user-images.githubusercontent.com/21026700/47119024-06622480-d272-11e8-8753-83c270c5d82b.png)

The code runs successfully and an exception is thrown at the very end.
Thank.

**Comment by deniszykov** [comment] 2018-10-18 08:05
Hi @GusevVasily! It seems WS's underlying Socket has been shutdown while/before writing actual message. This could be result of Dispose() call on WS instance. To properly close connection you need CloseAsync(), then Dispose(). That could be done to find source of this exception:
1) disable Deflate extension
2) add logging before each Dispose/CloseAsync call and trace where WS is disposed.

**Comment by gusevvasily** [comment] 2018-10-18 12:41
@deniszykov 
1. I can't disable Deflate, at once, at start, writes the warning:
![screenshot_105](https://user-images.githubusercontent.com/21026700/47154228-6399bc80-d2ea-11e8-9f40-115cd5540546.png)
2. I wrote this code logging:
![screenshot_110](https://user-images.githubusercontent.com/21026700/47154882-351ce100-d2ec-11e8-96e5-dfbfcc95b37d.png)

The error stopped flying. But time after time started again and a lot. Apparently in all the queries where not flying:
![screenshot_109](https://user-images.githubusercontent.com/21026700/47154885-38b06800-d2ec-11e8-87ef-67f4b744053a.png)

**Comment by deniszykov** [comment] 2018-10-20 16:30
Actually I can't see why it's happening.  You need to trace it yourself. I found one more error in logic:
WS should be always read for new message, to make sure control frames (pings etc) are processed. Right after accepting WS instance  you need to decide what to do next:
а) close it with CloseAsync()
b) start read messages, then in parallel start writing messages.

**Comment by gusevvasily** [comment] 2018-10-20 16:39
@deniszykov 

I think it stopped appearing errors, in most of the cases. But that's not all, I noticed two bugs in the library:

1. If you send any message to the server and write a response to the client, the client will receive two messages: 1 - what he wrote to the server (the server returns the client message) and 2 - server response.
2. When processing a server response in javascript, the response is preceded by an incomprehensible "mystical space" character.
A screenshot is attached below:
![screenshot_121](https://user-images.githubusercontent.com/21026700/47258161-e1eb8f80-d49f-11e8-8258-967ef4f03f93.png)

Thank.

**Comment by gusevvasily** [comment] 2018-10-20 16:45
I noticed that in this case there is an exception:
![screenshot_122](https://user-images.githubusercontent.com/21026700/47258214-b1f0bc00-d4a0-11e8-98b1-49adae7b8ec9.png)

=======================================

![screenshot_123](https://user-images.githubusercontent.com/21026700/47258216-b6b57000-d4a0-11e8-9268-b0ffcfbd3e17.png)

**Comment by deniszykov** [comment] 2018-10-20 18:28
1) You need to review your code.

2) \ufeff is unicode [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) preamble. 
https://stackoverflow.com/questions/5266069/streamwriter-and-utf-8-byte-order-marks 

Original library and this fork do few things by itself: ping frames and socket handling. Other action like connecting/disconnecting, sending/receiving are performed by library user. Data is sent as is. If you send bytes, they will be sent as binary frame. If you send text, it would be encoded with UTF-8 and sent as text frame. 
Errors with unwanted data inside frame or unwanted frames should be looked in user code.

**Comment by gusevvasily** [comment] 2018-10-22 17:34
@deniszykov Hello

Can you tell me how to make a "newsletter" one message to all users? Tried to do through such code, not goes. The message, of course, is not sent to anyone:
![screenshot_129](https://user-images.githubusercontent.com/21026700/47308268-cb793b80-d639-11e8-8d95-6d352d6205e7.png)
![screenshot_130](https://user-images.githubusercontent.com/21026700/47308269-ccaa6880-d639-11e8-9c0b-5a0b217bb250.png)
![screenshot_131](https://user-images.githubusercontent.com/21026700/47308271-cddb9580-d639-11e8-87b5-ffa8f016fdf6.png)

Throws such an exception, which I sent above. That's what the problem was, it turns out:
![screenshot_132](https://user-images.githubusercontent.com/21026700/47308324-ec419100-d639-11e8-8aea-d2987390a5b7.png)

**Comment by deniszykov** [comment] 2018-10-22 17:57
1) By design only one writer/reader is allowed per WS instance, so you need some kind of synchronization mechanism. Here is original library author post https://github.com/vtortola/WebSocketListener/issues/120
2) Some WS instances could be dead because of timeout or partially closed from other side. You need to check their state before writing.
3) Some write operation could fail due network error. So try/catch is required.

TPL Dataflow is good start for synchronization and and handling messages.

Current WS implementation is quite raw. No safeguards, no synchronization or queues. Everything should be provided by user.

**Closed as completed** 2019-06-27 20:28 UTC
